ipc = true
splash = false

wallpaper {
    monitor = HDMI-A-1
    path = $HOME/.dotfiles/files/wallpapers/Waves.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = $HOME/.dotfiles/files/wallpapers/Waves.png
    fit_mode = cover
}

