#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <URL> [destination_folder] [playlist_start]"
    exit 1
fi

URL="$1"
DESTINATION_FOLDER="${2:-$HOME/Music/tmp}"
mkdir -p "$DESTINATION_FOLDER"
echo "Downloading to $DESTINATION_FOLDER"

PLAYLIST_START="${3:-1}"

yt-dlp -x --audio-format mp3 --audio-quality 0 -N 5 --embed-thumbnail --playlist-start=$PLAYLIST_START -o "$DESTINATION_FOLDER/%(title)s.%(ext)s" "$URL"
