# Tmux configuration


## Settings ====================================================================

set -ag terminal-overrides ",xterm*:RGB"  # RGB colors in xterm

set -g mouse on  # enable mouse support
set -g prefix C-b  # Tmux prefix
set -g repeat-time 1000  # prefix free time in milliseconds

set -g allow-passthrough on  # Programs can bypass tmux with escape sequence, e.g. kitty images

set -g visual-activity off  # No display of message on activity

# Start index of windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on


## Colors ======================================================================

set -g status-style bg=default,fg=default
set -g status-left "[#S] "
set -g status-right ""

# set -g window-status-format "•"
# set -g window-status-current-format "●"
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=default}"
set -g window-status-bell-style "fg=red"

## Keybindings =================================================================

# Enable vim keybindings
set-window-option -g mode-keys vi

# Mappings for pane navigation using Ctrl + hjkl
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

# Vertical and horizontal split into same directory
bind '"' split-window -v -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'
# New window in same directory
bind c new-window -c "#{pane_current_path}"

# ALT + number selects its window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10
bind -n M-F1  select-window -t:11
bind -n M-F2  select-window -t:12
bind -n M-F3  select-window -t:13
bind -n M-F4  select-window -t:14
bind -n M-F5  select-window -t:15
bind -n M-F6  select-window -t:16
bind -n M-F7  select-window -t:17
bind -n M-F8  select-window -t:18
bind -n M-F9  select-window -t:19
bind -n M-F10 select-window -t:20
bind -n M-F11 select-window -t:21
bind -n M-F12 select-window -t:22

# ALT + h or l switches to previous or next window, respectively
bind -n M-h previous-window
bind -n M-l next-window

# Scroll 1 line up or down with mouse wheel
bind -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X scroll-down


## Plugins =====================================================================

set -g @plugin 'tmux-plugins/tmux-sensible'  # Basic sensible defaults
set -g @plugin 'christoomey/vim-tmux-navigator'  # Navigate between tmux and nvim splits interchangeably
set -g @plugin 'tmux-plugins/tmux-yank'  # Copy to system clipboard

set -g @plugin 'tmux-plugins/tmux-resurrect'  # Save and restore tmux session
set -g @resurrect-capture-pane-contents 'on'

run '/usr/share/tmux-plugin-manager/tpm'

## Testing out TMUX stuff ======================================================

## Disable bells
set -g bell-action none

## Uncomment on different system to use different prefix key.
# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix

## Using mouse dragging to select stuff without leaving copy mode and selection
## stays as is.
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection -x

## Prefix, then `m`: Toggles monitoring the window, i.e. highlights it in status
## line as soon as something changes there.
bind m {
    set monitor-activity
    display 'Monitoring #{?monitor-activity,started,turned off}'
}

## Prefix, then `y`: Toggles synchronization of pane inputs.
bind y {
    set synchronize-panes
    display 'Synchronizing panes #{?synchronize-panes,started,turned off}'
}

set -g automatic-rename on
